"""migrate to oauth_accounts table

Revision ID: bd830c47d0ae
Revises: c5d2f0418f68
Create Date: 2026-03-18 11:49:13.678466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd830c47d0ae'
down_revision: Union[str, Sequence[str], None] = 'c5d2f0418f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create oauth_accounts table
    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='unique_provider_account'),
    sa.UniqueConstraint('user_id', 'provider', name='unique_user_provider')
    )
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_accounts_id'), ['id'], unique=False)

    # 2. Migrate existing OAuth data from users table to oauth_accounts
    connection = op.get_bind()
    result = connection.execute(
        sa.text(
            "SELECT id, oauth_providers, oauth_provider_id FROM users "
            "WHERE oauth_providers IS NOT NULL AND oauth_provider_id IS NOT NULL"
        )
    )
    
    for user_id, provider, provider_user_id in result:
        connection.execute(
            sa.text(
                "INSERT INTO oauth_accounts (user_id, provider, provider_user_id) "
                "VALUES (:user_id, :provider, :provider_user_id)"
            ),
            {"user_id": user_id, "provider": provider, "provider_user_id": provider_user_id}
        )
    
    # 3. Drop old columns
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('oauth_providers')
        batch_op.drop_column('oauth_provider_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('oauth_providers', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_id'))

    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
