"""add_oauth_fields_and_nullable_password

Revision ID: c5d2f0418f68
Revises: c84e98add0ef
Create Date: 2026-03-17 11:38:14.924154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d2f0418f68'
down_revision: Union[str, Sequence[str], None] = 'c84e98add0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_providers', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('oauth_provider_id', sa.String(), nullable=True))
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('oauth_provider_id')
        batch_op.drop_column('oauth_providers')

    # ### end Alembic commands ###
