"""Sample data used by the seed script."""

USERS = [
    {
        "email": "admin@example.com",
        "username": "admin",
        "password": "admin1234",
        "roles": ["admin", "user"],
    },
    {
        "email": "alice@example.com",
        "username": "alice",
        "password": "alice1234",
        "roles": ["user"],
    },
    {
        "email": "bob@example.com",
        "username": "bob",
        "password": "bob1234",
        "roles": ["user"],
    },
    {
        "email": "carol@example.com",
        "username": "carol",
        "password": "carol1234",
        "roles": ["user"],
    },
]

# owner_username references USERS above
POSTS = [
    {
        "title": "Getting started with FastAPI",
        "content": (
            "FastAPI is a modern, fast web framework for building APIs with Python. "
            "It leverages standard Python type hints for automatic validation and docs."
        ),
        "published": True,
        "rating": 5,
        "owner_username": "admin",
    },
    {
        "title": "SQLAlchemy ORM tips",
        "content": (
            "Using SQLAlchemy with FastAPI is straightforward. "
            "Always use dependency injection to manage sessions properly."
        ),
        "published": True,
        "rating": 4,
        "owner_username": "alice",
    },
    {
        "title": "JWT authentication deep dive",
        "content": (
            "Access tokens should be short-lived. "
            "Refresh tokens allow clients to obtain new access tokens without re-authenticating."
        ),
        "published": True,
        "rating": 5,
        "owner_username": "alice",
    },
    {
        "title": "Draft: Async Python patterns",
        "content": "Work in progress — comparing asyncio, trio and structured concurrency.",
        "published": False,
        "rating": None,
        "owner_username": "bob",
    },
    {
        "title": "Testing FastAPI with pytest",
        "content": (
            "Use TestClient for synchronous tests and override dependencies "
            "to inject an in-memory SQLite database. Keep tests isolated."
        ),
        "published": True,
        "rating": 4,
        "owner_username": "bob",
    },
    {
        "title": "Alembic migrations guide",
        "content": (
            "Alembic lets you version-control your database schema. "
            "Always review autogenerated migrations before applying them."
        ),
        "published": True,
        "rating": 3,
        "owner_username": "carol",
    },
]

# post_index references POSTS list above (0-based)
COMMENTS = [
    {
        "text": "Great intro, very clear!",
        "upvotes": 12,
        "downvotes": 0,
        "post_index": 0,
        "owner_username": "alice",
    },
    {
        "text": "Would love a follow-up post on async endpoints.",
        "upvotes": 5,
        "downvotes": 1,
        "post_index": 0,
        "owner_username": "bob",
    },
    {
        "text": "The session management tip saved me a lot of debugging time.",
        "upvotes": 8,
        "downvotes": 0,
        "post_index": 1,
        "owner_username": "carol",
    },
    {
        "text": "Make sure to store refresh tokens securely (HttpOnly cookie).",
        "upvotes": 15,
        "downvotes": 2,
        "post_index": 2,
        "owner_username": "admin",
    },
    {
        "text": "Good point about short-lived access tokens.",
        "upvotes": 6,
        "downvotes": 0,
        "post_index": 2,
        "owner_username": "carol",
    },
    {
        "text": "The conftest.py pattern with dependency override is neat.",
        "upvotes": 9,
        "downvotes": 1,
        "post_index": 4,
        "owner_username": "alice",
    },
    {
        "text": "Always run `alembic check` in CI to catch unapplied migrations.",
        "upvotes": 7,
        "downvotes": 0,
        "post_index": 5,
        "owner_username": "bob",
    },
]
